[versions]
org-springframework-boot = "3.1.10"

[libraries]
org-springframework-spring-framework-bom = "org.springframework:spring-framework-bom:6.0.18"
org-springframework-security-spring-security-bom = "org.springframework.security:spring-security-bom:6.1.7"
org-springframework-data-spring-data-bom = "org.springframework.data:spring-data-bom:2022.0.12"
org-springframework-security-spring-security-oauth2-authorization-server = "org.springframework.security:spring-security-oauth2-authorization-server:1.0.4"

[plugins]
io-spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.4" }
org-springframework-boot = { id = "org.springframework.boot", version.ref = "org-springframework-boot" }
