[versions]
org-springframework-boot = "3.2.3"

[libraries]
org-springframework-spring-framework-bom = "org.springframework:spring-framework-bom:6.1.5"
org-springframework-security-spring-security-bom = "org.springframework.security:spring-security-bom:6.3.0-SNAPSHOT"
org-springframework-data-spring-data-bom = "org.springframework.data:spring-data-bom:2023.1.4"
org-springframework-security-spring-security-oauth2-authorization-server = "org.springframework.security:spring-security-oauth2-authorization-server:1.2.2"

[plugins]
io-spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.4" }
org-springframework-boot = { id = "org.springframework.boot", version.ref = "org-springframework-boot" }
